name: Build Sahaji App
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pymupdf pillow pyinstaller pywin32
      - name: Create EXE
        run: |
          pyinstaller --noconsole --onefile main.py
      - name: Upload Software
        uses: actions/upload-artifact@v4
        with:
          name: Sahaji-NetPoint-App
          path: dist/main.exe
